[build]
  command = "npm install && npm run lint && npm run build"
  publish = "dist/"
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ["main", "algolia"]
  template = "hierarchical"
