menu:
  docs:
    - name: Intro
      title: Intro to Decap CMS
    - name: Add
      title: Add To Your Site
    - name: Accounts
      title: Account Settings
    - name: Configuration
      title: Configuring your Site
    - name: Media
      title: Media
    - name: Workflow
      title: Workflow
    - name: Collections
      title: Collections
    - name: Widgets
      title: Widgets
    - name: Guides
      title: Platform Guides
    - name: Customization
      title: Customizing Decap CMS
    - name: Contributing
      title: Community
